version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  decoder:
      build: ./video_decoder
      image: stinquisitor/decoder:latest
      command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
      volumes:
          - ./video_decoder/app:/code/app
      ports:
          - 8004:8000
      env_file:
        - ./video_decoder/.env

